---
title: "Homework 2"
author: "Lupe Antonio"
date: "10/2/2023"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```


## Problem 1

```{r, message=FALSE}
#loading pols-month data
pols_month <- read_csv("data_hw2/fivethirtyeight_datasets/pols-month.csv")
```

```{r}
#cleaning the data
pols_month <- janitor::clean_names(pols_month) %>%
  #breaking up variable mon into integer variables: year, month, & day
  separate(mon, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(
    #replacing month num with month name
    month = case_match(
      month,
      1 ~ "january",
      2 ~ "february",
      3 ~ "march", 
      4 ~ "april",
      5 ~ "may",
      6 ~ "june",
      7 ~ "july",
      8 ~ "august",
      9 ~ "september",
      10 ~ "october",
      11 ~ "november",
      12 ~ "december"),
    #creating president variable
    president = case_when(
      prez_dem == 1 & prez_gop == 0 ~ "democratic",
      prez_dem == 0 & prez_gop == 1 ~ "republican")) %>%
  #removing prez_dem, prez_gop, and day variables
  select(-prez_dem, -prez_gop, -day)
```


```{r, message=FALSE}
#loading snp.csv data
snp <- read_csv("data_hw2/fivethirtyeight_datasets/snp.csv") %>%
  #cleaning data
  janitor::clean_names() %>%
  #fixing the dates
  mutate(date = lubridate::mdy(date)) %>%
  #breaking up date variable into integer variables: year, month, day
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(
    #replacing month num with month name
    month = case_match(
      month,
      1 ~ "january",
      2 ~ "february",
      3 ~ "march", 
      4 ~ "april",
      5 ~ "may",
      6 ~ "june",
      7 ~ "july",
      8 ~ "august",
      9 ~ "september",
      10 ~ "october",
      11 ~ "november",
      12 ~ "december")) %>%
  #removing day variable
  select(-day)
```


```{r, message=FALSE}
#loading unemployment.csv data
unemployment <- read_csv("data_hw2/fivethirtyeight_datasets/unemployment.csv") %>%
  #cleaning the data
  janitor::clean_names() %>%
  #going from "wide" to "long" format
  pivot_longer(jan:dec,
               names_to = "month",
               values_to = "unemp_perctg") %>%
  #fixing month names
  mutate(
    month = case_match(
      month,
      "jan" ~ "january",
      "feb" ~ "february",
      "mar" ~ "march",
      "apr" ~ "april",
      "may" ~ "may",
      "jun" ~ "june",
      "jul" ~ "july",
      "aug" ~ "august",
      "sep" ~ "september",
      "oct" ~ "october",
      "nov" ~ "november",
      "dec" ~ "december"
    ))
```

Join the datasets by merging snp into pols, and merging unemployment into the result.

Write a short paragraph about these datasets. Explain briefly what each dataset contained, and describe the resulting dataset (e.g. give the dimension, range of years, and names of key variables).